FROM mongo:3.2
WORKDIR /app
RUN mkdir -p /tmp/smart_backup
RUN echo "Asia/Shanghai" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata
RUN apt-get update
RUN apt-get install -y ca-certificates
CMD ["mongod"]
