FROM mongo:3.2
#WORKDIR /app
RUN echo "Asia/Shanghai" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata
#RUN apt-get update
#RUN apt-get install -y ca-certificates
CMD ["mongod"]
#docker  run -it -p 27017:27017  mongo:3.2 sh -c "mongod"
