# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/log_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/log_request.proto',
  package='protos',
  syntax='proto3',
  serialized_pb=_b('\n\x18protos/log_request.proto\x12\x06protos\"9\n\x03Log\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07logData\x18\x02 \x01(\x0c\x12\x13\n\x0b\x64\x65layTimeMs\x18\x03 \x01(\x05\"\'\n\nLogRequest\x12\x19\n\x04logs\x18\x01 \x03(\x0b\x32\x0b.protos.LogB%\n\x11\x63om.apkpure.protoB\x10LogRequestProtosb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOG = _descriptor.Descriptor(
  name='Log',
  full_name='protos.Log',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='protos.Log.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='logData', full_name='protos.Log.logData', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delayTimeMs', full_name='protos.Log.delayTimeMs', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=93,
)


_LOGREQUEST = _descriptor.Descriptor(
  name='LogRequest',
  full_name='protos.LogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='logs', full_name='protos.LogRequest.logs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=134,
)

_LOGREQUEST.fields_by_name['logs'].message_type = _LOG
DESCRIPTOR.message_types_by_name['Log'] = _LOG
DESCRIPTOR.message_types_by_name['LogRequest'] = _LOGREQUEST

Log = _reflection.GeneratedProtocolMessageType('Log', (_message.Message,), dict(
  DESCRIPTOR = _LOG,
  __module__ = 'protos.log_request_pb2'
  # @@protoc_insertion_point(class_scope:protos.Log)
  ))
_sym_db.RegisterMessage(Log)

LogRequest = _reflection.GeneratedProtocolMessageType('LogRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGREQUEST,
  __module__ = 'protos.log_request_pb2'
  # @@protoc_insertion_point(class_scope:protos.LogRequest)
  ))
_sym_db.RegisterMessage(LogRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.apkpure.protoB\020LogRequestProtos'))
# @@protoc_insertion_point(module_scope)
