# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import youtube_pb2 as youtube__pb2


class GreeterStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.YoutubeWatch = channel.unary_unary(
        '/protos.Greeter/YoutubeWatch',
        request_serializer=youtube__pb2.YoutubeWatchRequest.SerializeToString,
        response_deserializer=youtube__pb2.YoutubeWatchReply.FromString,
        )


class GreeterServicer(object):
  """The greeting service definition.
  """

  def YoutubeWatch(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'YoutubeWatch': grpc.unary_unary_rpc_method_handler(
          servicer.YoutubeWatch,
          request_deserializer=youtube__pb2.YoutubeWatchRequest.FromString,
          response_serializer=youtube__pb2.YoutubeWatchReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
