FROM python:3-alpine
#ffmpeg 音频和视频的解码器库
RUN apk add --no-cache ffmpeg && pip3 install you-get && mkdir -p /downloads
WORKDIR /downloads
VOLUME /downloads

#ENTRYPOINT [ "you-get" ]
CMD [ "you-get", "--help" ]
