#v4tech/imagemagick
#jess/imagemagick
FROM v4tech/imagemagick
MAINTAINER huoyinghui "huoyinghui@qpkpure.com"
WORKDIR /app
RUN mkdir -p /app/conf
#COPY conf /app/conf
#COPY build/linux-amd64/log-collect /app/log-collect
CMD ["convert --version"]